<?xml version="1.0"?>
<package format="3">
<name>tulip_bridge</name>
<version>0.0.1</version>
<description>UDP bridge between ROS2 and Tulip ESP32 robot</description>
<maintainer email="asrabelajar@gmail.com">prhayogo</maintainer>
<license>Apache-2.0</license>
<exec_depend>rclpy</exec_depend>
<exec_depend>geometry_msgs</exec_depend>
<exec_depend>sensor_msgs</exec_depend>
<exec_depend>nav_msgs</exec_depend>
<build_depend>python3</build_depend>
<export><build_type>ament_python</build_type></export>
</package>
